### ISSUE TITLE
Updating the existing Tkinter based GUI

### ISSUE THREAD

**Issue by akshgpt7** [Marauders-9998/Attendance-Management-using-Face-Recognition#13]
The current Tkinter GUI looks dull and basic. It should include better color schemes, better positioning and sizing of elements. It would be a great update to the current GUI :)

**Comment by Vibhu-Agarwal** [comment]
Any design you have any mind?
Please upload a picture of the same.

**Comment by akshgpt7** [comment]
I've come up with something like this. I can change the colors as per your liking :) 
![Screenshot from 2019-10-27 04-23-41](https://user-images.githubusercontent.com/20405311/67627001-d7619400-f871-11e9-9d1c-c095b2be0f4b.png)

**Comment by akshgpt7** [comment]
I can edit it further as per your liking :)

**Comment by Vibhu-Agarwal** [comment]
@akshgpt7 Sorry for the late response.
About your proposed design:
- `Show` button beside Password field can be helpful. Implementing it can be treated as a separate feature in itself. Go ahead, raise a new issue for it and start implementing it right away.
- About the changed size and orientation of buttons, it is apt to make the two portal buttons more appealing so +1 for orientation. But try to make it them look less out-of-place. Try reducing their size.
- About the colors, the whole theme will have to be modified and not just the Home Screen, for all screens. If you could make it look a bit more professional with proper matching colors (look for material), that would be great.

**Comment by Vibhu-Agarwal** [comment]
@akshgpt7 Sorry for the late response.
About your proposed design:
- `Show` button beside Password field can be helpful. Implementing it can be treated as a separate feature in itself. Go ahead, raise a new issue for it and start implementing it right away.
- About the changed size and orientation of buttons, it is apt to make the two portal buttons more appealing so +1 for orientation. But try to make it them look less out-of-place. Try reducing their size.
- About the colors, the whole theme will have to be modified and not just the Home Screen, for all screens. If you could make it look a bit more professional with proper matching colors (look for material), that would be great.

**Comment by akshgpt7** [comment]
Thanks for the review. Will start working on it!
