### ISSUE TITLE
Update Application Images in README

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [Marauders-9998/Attendance-Management-using-Face-Recognition#21]
After complete revamping (#14) of the UI of the application, the screenshots of different screens need to be updated in the README

**Comment by agrima84** [comment]
I would like to work on this issue

**Comment by Vibhu-Agarwal** [comment]
> I would like to work on this issue

Hi @agrima84 
Please join our slack channel for the discussions on the project :)
(You can do so by clicking on the Slack badge on the README)
