### ISSUE TITLE
Steps for training the model and capturing the images 

### ISSUE THREAD

**Issue by gangubai** [Marauders-9998/Attendance-Management-using-Face-Recognition#6]
ak@Ak-Inspiron-3542:~/A_Projects/Attendance-Management-using-Face-Recognition-master$ python3 Attendance_app.py 
current class Marauders
current class Marauders
ak@Aki-Inspiron-3542:~/A_Projects/Attendance-Management-using-Face-Recognition-master$ python3 capture.py 
ak@Ak-Inspiron-3542:~/A_Projects/Attendance-Management-using-Face-Recognition-master$ python face_train.py 
ak@Ak-Inspiron-3542:~/A_Projects/Attendance-Management-using-Face-Recognition-master$ python3 capture.py 

Like after running these python files I am not getting anything for either capturing the image or for training the images ...also i explicitly give the images in the batchwise roll no folder.....
Thanks!

**Comment by Vibhu-Agarwal** [comment]
@gangubai Hi!
Thanks for opening this issue and sorry from our part for a very late response.
To run the app, the only command you got to run is for the `Attendance_app.py`
Rest of training and capturing images can be done through GUI of the app.
You can read the [README](https://github.com/Marauders-9998/Attendance-Management-using-Face-Recognition/blob/master/README.md) to see how to go around with the app.
The several functions are triggered on the press of those buttons.

If you want to see how it happens behind it, you can view the code-base and try to figure out which functions are being called and what other actions are being performed on those button press, thereby getting the idea how to do it through scripts on your own and even contribute to this project.
